name: Linting

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  selene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest selene version
        id: selene-version
        run: |
          echo "SELENE_VERSION=$(curl -s -L0 https://crates.io/api/v1/crates/selene  | jq -r '.crate.max_stable_version')" >> $GITHUB_ENV

      - name: Restore Cached Selene
        id: cache-selene-restore
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-selene-${{ env.SELENE_VERSION }}
          path: ~/.cargo/bin/selene

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        if: ${{ steps.cache-selene-restore.outputs.cache-hit != 'true' }}
        with:
          toolchain: stable

      - name: Install Selene
        if: ${{ steps.cache-selene-restore.outputs.cache-hit != 'true' }}
        run: cargo install selene --force

      - name: Run Selene
        run: make lint

  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check lua/ tests/
